=== PetalsLinkLabs/petals-dsb/distributions/dsb-wsdm-distribution/src/main/packaging/schema/petalsTopology.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://petals.ow2.org/topology"
	xmlns:tns="http://petals.ow2.org/topology" elementFormDefault="qualified">
	<complexType name="Topology">
		<sequence>
			<element name="domain" type="tns:Domain" minOccurs="1"
				maxOccurs="1">
				<annotation>
					<documentation>
						A PEtALS domain. Each member share its data and
						communicate with other members.
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="Domain">
		<sequence>
			<element name="description" type="string" default="description of this domain"
				maxOccurs="1" minOccurs="0" />
			<element name="multicast" type="tns:Multicast" maxOccurs="1"
				minOccurs="0">
				<annotation>
					<documentation>
						This tag is related to the PEtALS network. When
						declared, this tag defines the UDP multicast
						channel whom PEtALS nodes broacast messages to
						synchronize their data. If not declared, the
						nodes use dedicated connections by TCP unicast
						channels. If you want to use a large number of
						nodes, it can be interesting to define this tag
						to avoid huge dedicated TCP connections. Note
						that some networks forbids UDP multicast
						messages.Do not declare this tag in 'standalone'
						domain mode.
					</documentation>
				</annotation>
			</element>
			<element name="jndi" type="tns:Jndi" maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>
						The JNDI directory shared among the PEtALS
						domain. If not declared, the internal PEtALS
						JNDI directory is used. If you want to connect
						the PEtALS domain to an external JNDI directory,
						specify the the JNDI parameters. Refer to JNDI
						specifications for more details.
					</documentation>
				</annotation>
			</element>
			<element name="sub-domain" type="tns:Subdomain" maxOccurs="unbounded"
				minOccurs="1">
				<annotation>
					<documentation>
						A PEtALS subdomain. PEtALS nodes can expose
						their services into 'public' or 'private' area.
						'public' services are reachable by the entire
						PEtALS domain whereas 'private' service are
						reachable only by members of the same subdomain.
						Not used in 'standalone' domain mode.
					</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="mode" type="tns:DomainMode" use="required">
			<annotation>
				<documentation>
					Three domain mode are available. The 'standalone'
					mode allows an unique node within the domain. In
					this mode the domain is lighten by getting ride of
					the Network, Joram and Dream services. The 'dynamic'
					mode allows any no/de connecting to the PEtALS
					network to join the domain. In multicast network,
					you just have to define your local node in the
					topology. In unicast network, you must specify
					additionally the nodes that would be your
					coordinators; at least one of these node must run
					when you launch your local node. The 'static' domain
					accepts only the nodes defined in the topology. Each
					node of the domain must have the same topology
					definition.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="name" type="string" use="required" />
	</complexType>
	<simpleType name="DomainMode">
		<restriction base="string">
			<enumeration value="static" />
			<enumeration value="dynamic" />
			<enumeration value="standalone" />
		</restriction>
	</simpleType>
	<complexType name="Multicast">
		<all>
			<element name="ip" type="string" maxOccurs="1" minOccurs="1"
				default="224.7.65.50" />
			<element name="port" type="int" maxOccurs="1" minOccurs="1"
				default="4000" />
		</all>
	</complexType>
	
	<complexType name="Jndi">
		<all>
			<element name="factory" type="string" maxOccurs="1"
				minOccurs="1"
				default="org.objectweb.petals.communication.jndi.connection.NamingContextFactory" />
			<element name="provider-url" type="string" maxOccurs="1" minOccurs="1" />
			<element name="security-principal" type="string" maxOccurs="1" minOccurs="0" />
			<element name="security-credentials" type="string" maxOccurs="1" minOccurs="0" />
			<element name="pool-size" type="int" maxOccurs="1" minOccurs="0" />
			<element name="batch-size" type="int" maxOccurs="1" minOccurs="0" />
		</all>
	</complexType>
	<complexType name="Subdomain">
		<sequence>
			<element name="description" type="string" default="description of this domain"
				maxOccurs="1" minOccurs="0" />
			<element name="network-time-synchronized" type="boolean"
				maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>
						Set to true if the hosts running the PEtALS
						sub-domain are timed-synchronized (using NTP
						for example). Default value is false.
					</documentation>
				</annotation>
			</element>
			<element name="container" type="tns:Container" maxOccurs="unbounded"
				minOccurs="1">
				<annotation>
					<documentation>
						Define a PEtALS node. It contains the definition
						of security, management and communication
						resources.
					</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	<complexType name="Container">
		<all>
			<element name="description" type="string" default="description of this domain"
				maxOccurs="1" minOccurs="0" />
			<element name="host" type="string" maxOccurs="1" minOccurs="1"
				default="localhost">
				<annotation>
					<documentation>
						Define the IP address or host name of the
						container.
					</documentation>
				</annotation>
			</element>
			<element name="user" type="string" maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>
						Define the user to be used for JMX and Joram
						clients.
					</documentation>
				</annotation>
			</element>
			<element name="password" type="string" maxOccurs="1"
				minOccurs="0">
				<annotation>
					<documentation>
						Define the password to be used for JMX and Joram
						clients.
					</documentation>
				</annotation>
			</element>
			<element name="network-service" type="tns:NetworkService"
				maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>
						Define the port to listen for PEtALS
						network messages. In multicast network, the
						messages are only responses whereas in unicast
						network, it can be any messages. Do not declare
						this tag in 'standalone' domain mode.
					</documentation>
				</annotation>
			</element>
			<element name="jmx-service" type="tns:JmxService" maxOccurs="1"
				minOccurs="1">
				<annotation>
					<documentation>
						Define the JMX required ports.
					</documentation>
				</annotation>
			</element>
			<element name="transport-service" type="tns:TransportService"
				maxOccurs="1" minOccurs="0">
				<annotation>
					<documentation>
						Define the Transport required port. Do not declare
						this tag in 'standalone' domain mode.
					</documentation>
				</annotation>
			</element>
		</all>
		<attribute name="name" type="string" use="required" />
	</complexType>
	<complexType name="NetworkService">
		<sequence>
			<element name="port" type="int" maxOccurs="1" minOccurs="1" />
		</sequence>
	</complexType>
	<complexType name="JmxService">
		<all>
			<element name="rmi-port" type="int" maxOccurs="1" minOccurs="1" />
		</all>
	</complexType>
	<complexType name="TransportService">
		<sequence>
			<element name="tcp-port" type="int" maxOccurs="1" minOccurs="0" />
			<element name="ssl-port" type="int" maxOccurs="1" minOccurs="0" />
			<element name="http-port" type="int" maxOccurs="1" minOccurs="0" />
		</sequence>
	</complexType>
	<element name="topology" type="tns:Topology">
		<annotation>
			<documentation>
				The PEtALS topology. It contains information about the
				resources and configurations required by your PEtALS
				nodes. PEtALS node local setting are defined independently
				in the file 'server.properties'
			</documentation>
		</annotation>
	</element>
</schema>

=== PetalsLinkLabs/petals-dsb/samples/dsb-custom/custom-distrib/src/main/packaging/dsbconfig/ovh/topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:topology xmlns:tns="http://petals.ow2.org/topology"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://petals.ow2.org/topology petalsTopology.xsd">
	<tns:domain mode="static" name="PEtALS">
		<tns:description>The static domain configuration</tns:description>
		<!--
			defaut configuration to use MySql as centralize petals registry
			<tns:jndi>
			<tns:factory>org.ow2.petals.registry.database.RegistryInitialContextFactory</tns:factory>
			<tns:provider-url>jdbc:mysql://localhost:3306/mysql</tns:provider-url>
			<tns:security-principal>root</tns:security-principal>
			<tns:security-credentials>mysql</tns:security-credentials>
			<tns:pool-size>5</tns:pool-size> <tns:batch-size>10</tns:batch-size>
			</tns:jndi>
		-->
		<tns:sub-domain name="subdomain1">
			<tns:description>description of the subdomain</tns:description>
			<tns:container name="SOA4ALL-EBM-00">
				<tns:description>description of the EBMWS container 0
				</tns:description>
				<tns:host>soa4all.ebmwebsourcing.com</tns:host>
				<tns:user>petals</tns:user>
				<tns:password>petals</tns:password>
				<tns:webservice-service>
					<tns:port>7600</tns:port>
					<tns:prefix>petals/ws</tns:prefix>
				</tns:webservice-service>
				<tns:jmx-service>
					<tns:rmi-port>7700</tns:rmi-port>
				</tns:jmx-service>
				<tns:transport-service>
					<tns:tcp-port>7800</tns:tcp-port>
				</tns:transport-service>
				<tns:registry-service>
					<tns:port>7900</tns:port>
				</tns:registry-service>
			</tns:container>

			<tns:container name="SOA4ALL-INRIA-00">
				<tns:description>description of the INRIA container 0
				</tns:description>
				<tns:host>trinidad.inria.fr</tns:host>
				<tns:user>petals</tns:user>
				<tns:password>petals</tns:password>
				<tns:webservice-service>
					<tns:port>7600</tns:port>
					<tns:prefix>petals/ws</tns:prefix>
				</tns:webservice-service>
				<tns:jmx-service>
					<tns:rmi-port>7700</tns:rmi-port>
				</tns:jmx-service>
				<tns:transport-service>
					<tns:tcp-port>7800</tns:tcp-port>
				</tns:transport-service>
				<tns:registry-service>
					<tns:port>7900</tns:port>
					<!-- service is under services/RegistryService -->
				</tns:registry-service>
			</tns:container>

			<tns:container name="SOA4ALL-OVH-00">
				<tns:description>description of the container 1</tns:description>
				<tns:host>ns306320.ovh.net</tns:host>
				<tns:user>petals</tns:user>
				<tns:password>petals</tns:password>
				<tns:webservice-service>
					<tns:port>7600</tns:port>
					<tns:prefix>petals/ws</tns:prefix>
				</tns:webservice-service>
				<tns:jmx-service>
					<tns:rmi-port>7700</tns:rmi-port>
				</tns:jmx-service>
				<tns:transport-service>
					<tns:tcp-port>7800</tns:tcp-port>
				</tns:transport-service>
				<tns:registry-service>
					<tns:port>7900</tns:port>
					<!-- service is under services/RegistryService -->
				</tns:registry-service>
			</tns:container>

			<tns:container name="SOA4ALL-UIBK-00">
				<tns:description>description of the container 1</tns:description>
				<tns:host>soa4all-runtime.sti2.at</tns:host>
				<tns:user>petals</tns:user>
				<tns:password>petals</tns:password>
				<tns:webservice-service>
					<tns:port>7600</tns:port>
					<tns:prefix>petals/ws</tns:prefix>
				</tns:webservice-service>
				<tns:jmx-service>
					<tns:rmi-port>7700</tns:rmi-port>
				</tns:jmx-service>
				<tns:transport-service>
					<tns:tcp-port>7800</tns:tcp-port>
				</tns:transport-service>
				<tns:registry-service>
					<tns:port>7900</tns:port>
					<!-- service is under services/RegistryService -->
				</tns:registry-service>
			</tns:container>

		</tns:sub-domain>
	</tns:domain>
</tns:topology>

=== PetalsLinkLabs/petals-dsb/forks/wsdm-monitoring/petals4monitoring/monitoring.petals.standalone.distribution/src/main/packaging/conf/topology.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:topology xmlns:tns="http://petals.ow2.org/topology"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://petals.ow2.org/topology petalsTopology.xsd">
	<tns:domain mode="standalone" name="PEtALS">
	<tns:description>standalone topology</tns:description>
		<!-- the internal jndi server is used by default
			<tns:jndi>
			<tns:factory>org.ow2.petals.communication.jndi.client.naming.NamingContextFactory</tns:factory>
			<tns:host>host</tns:host>
			<tns:port>0</tns:port>
			</tns:jndi>
		-->
		<tns:sub-domain name="subdomain1" mode="standalone">
			<tns:container name="0" type="standalone">
				<tns:host>localhost</tns:host>
				<tns:description>description of the features of the Standalone container</tns:description>
				<tns:user>petals</tns:user>
				<tns:password>petals</tns:password>
				<tns:webservice-service>
					<tns:port>7600</tns:port>
					<tns:prefix>petals/ws</tns:prefix>
				</tns:webservice-service>
				<tns:jmx-service>
					<tns:rmi-port>7700</tns:rmi-port>
				</tns:jmx-service>
				<tns:registry-service>
					<tns:port>7900</tns:port>
				</tns:registry-service>
			</tns:container>
		</tns:sub-domain>
	</tns:domain>
</tns:topology>
